model.name=en_PP-OCRv5_mobile_rec
model.archive.url=https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0.0/en_PP-OCRv5_mobile_rec_infer.tar
model.archive.size=8007680
model.archive.sha256=e595b4cf2ffad19fbb5a61ba345d63939577a3ab8717b6e5995642590c9101b4
conversion.tool=Paddle2ONNX-2.1.0
conversion.opset=17
conversion.onnx.size=7843511
conversion.onnx.sha256=70b2450eed39599af6b996c27a2f1a0ef30eeb49f9f66dd3e74f28f652befc89
runtime.format=ONNX
runtime.format.size=7843511
runtime.format.sha256=70b2450eed39599af6b996c27a2f1a0ef30eeb49f9f66dd3e74f28f652befc89
dictionary.source=inference.yml.PostProcess.character_dict
dictionary.entries=436
dictionary.appended.space=true
dictionary.size=1416
dictionary.sha256=e025a66d31f327ba0c232e03f407ae8d105e1e709e7ccb3f408aa778c24e70d6
license=Apache-2.0
scope=offline-session-private-word-recognition-only
runtime.name=ONNX-Runtime-Android
runtime.version=1.28.0
runtime.aar.size=45634470
runtime.aar.sha256=f351a0638696f54b35184290dbc001d66daae17281ad0b548d2c70347d53b8a9
runtime.minSdk=24
runtime.telemetry.disabled=true
